version: '3'

services:
  smart-irrigation:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smart-irrigation
    ports:
      - "7860:7860"
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=Asia/Shanghai
