version: '3.8'

services:
  smart-irrigation:
    image: registry.cn-hangzhou.aliyuncs.com/nullskymc/smart-irrigation:latest
    container_name: smart-irrigation
    restart: unless-stopped
    ports:
      - "7860:7860"
    environment:
      - TZ=Asia/Shanghai
      - PYTHONUNBUFFERED=1
    volumes:
      - ./logs:/app/logs
      - ./config.yaml:/app/config.yaml
